#01-DEVOPS-Nginx-Deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-devops
  labels:
    app: eks-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-gitops
  template:
    metadata:
      labels:
        app: eks-gitops
    spec:
      containers:
        - name: eks-gitops
          image: 851844343568.dkr.ecr.us-east-1.amazonaws.com/docker_nodejs_demo:latest
          ports:
            - containerPort: 3000

