apiVersion: v1
kind: Service
metadata:
  name: eks-gitops
  labels:
    app: eks-gitops
spec:
  type: LoadBalancer
  selector:
    app: eks-gitops
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

